MarvelProject/MarvelProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("apps.personajes.urls", namespace="personajes"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MarvelProject/apps/personajes/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import (
    prueba1, CreatePersonajeView, ListPersonajeView,
    PersonajeDetail, PersonajeUpdateView, pull_data_marvel)



app_name = "personajes"

urlpatterns = [
    path("", prueba1, name="prueba"),
    path("get-datos", pull_data_marvel, name="datos"),
    path("crear-personaje", CreatePersonajeView.as_view(), name="crear-personaje"),
    path("creado/", TemplateView.as_view(template_name="personajes/creado.html"), name="creado"),
    path("list-personajes/", ListPersonajeView.as_view(), name="list"),
    path("detail-personajes/<int:pk>", PersonajeDetail.as_view(), name="detail"),
    path("update-personaje/<int:pk>", PersonajeUpdateView.as_view(), name="update"),
]

MarvelProject/apps/personajes/models.py
from django.db import models
from apps.utils.utils import user_directory_path
from django.urls import reverse


HEROE = "HEROE"
VILLANO = "VILLANO"

TIPOS = (
    (HEROE, "HEROE"),
    (VILLANO, "VILLANO")
)


class Personaje(models.Model):
    """
    Personajes de Marvel: Ejemplo: Wolverine
    """
    nombre = models.CharField(max_length=200)
    tipo_personaje = models.CharField(max_length=200, choices=TIPOS)
    descripcion = models.TextField()
    imagen = models.ImageField(upload_to=user_directory_path, blank=True, null=True)
    imagen_url = models.URLField(blank=True, null=True)
    url = models.URLField(blank=True, null=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre


    def get_absolute_url(self):
        return reverse('personajes:detail', kwargs={'pk': self.pk})



class Comic(models.Model):
    """
    Un personaje puede estar en muchos Comics,
    Y un Comic puede tener muchos personajes
    """
    nombre = models.CharField(max_length=200)
    url = models.URLField()
    personajes = models.ManyToManyField(Personaje)

    def __str__(self):
        return self.nombre

MarvelProject/apps/personajes/forms.py
from django import forms
from .models import TIPOS


class PersonajeForm(forms.Form):
    """
    Formulario de los Personajes
    """
    nombre = forms.CharField(widget=forms.TextInput(attrs={
        "class": "validate", "placeholder": "Escribe aquí el Nombre del personaje",
        "id":"nombre"
        }))
    tipo_personaje = forms.ChoiceField(choices=TIPOS)
    imagen = forms.ImageField()
    descripcion = forms.CharField(widget=forms.Textarea(
        attrs={'class': 'materialize-textarea', "placeholder": "Describe tu Personaje",}))
    

MarvelProject/apps/personajes/views.py
from django.shortcuts import render
from django.views.generic import View, ListView, DetailView, UpdateView
from django.http import HttpResponseRedirect
from .forms import PersonajeForm
from .models import Personaje
import datetime
from apps.utils.api_marvel import get_data


def prueba1(request):
    """
    Permite renderizar mi Primer template
    """
    title = "Este es mi Primer Template"
    date = datetime.datetime.now()
    template_name = 'personajes/index.html'
    return render(request, template_name, context={"title": title, 'date': date})


def pull_data_marvel(request):
    """
    Permite cargar nuevos elementos desde la 
    API de Marvel
    """
    template_name = 'personajes/extraer_data.html'
    if request.method == 'GET':
        return render(request, template_name)
    elif request.method == 'POST':
        datos = get_data()
        for data in datos:
            Personaje.objects.create(
                nombre=data.nombre,
                descripcion=data.descripcion,
                imagen_url=data.imagen_url,
                url=data.url,
                tipo_personaje="HEROE",
            )
        return HttpResponseRedirect('/list-personajes')

class CreatePersonajeView(View):
    """
    Permite crear un nuevo personaje de Marvel
    """
    template_name = 'personajes/crear.html'
    form_class = PersonajeForm

    def get(self, request, *args, **kwargs):
        """
        Visualiza el template
        """
        title = "Creación de un personaje Marvel"
        tipos = ["HEROE", "VILLANO"]
        return render(request, self.template_name, context={
            'title': title, 'form':self.form_class,
            'tipos': tipos})

    def post(self, request, *args, **kwargs):
        """
        Crea un nuevo Personaje
        """
        form = PersonajeForm(request.POST, request.FILES)
        if form.is_valid():
            personaje = Personaje(
                nombre=form.cleaned_data['nombre'],
                imagen=form.cleaned_data['imagen'],
                descripcion=form.cleaned_data['descripcion'],
                tipo_personaje=form.cleaned_data['tipo_personaje'],
            )
            personaje.save()
            return HttpResponseRedirect("/list-personajes")
        return render(request, self.template_name, {"form": form})


class ListPersonajeView(ListView):
    """
    Lista todos los Personajes de Marvel
    """
    template_name = 'personajes/list-personaje.html'
    model = Personaje
    paginate_by = 100

    def get_queryset(self):
        return Personaje.objects.all().order_by('-fecha_creacion')


class PersonajeDetail(DetailView):
    """
    Detalla Nuestro Personaje
    """
    template_name = 'personajes/detail-personaje.html'
    model = Personaje


class PersonajeUpdateView(UpdateView):
    """
    Permite actualizar un Personaje
    """
    template_name = 'personajes/update-personaje.html'
    model = Personaje
    fields = ['nombre', 'tipo_personaje', 'descripcion', 'imagen']

MarvelProject/apps/personajes/templates/personajes/creado.html
{% extends 'personajes/index.html' %}
{% load static%}

{% block container %}
<div class="card center">
    <div class="card-content">
        <h1 class="red-text text-darken-2">Tu personaje Ha sido Creado Satisfactoriamente</h1>
    </div>
    <div class="imagen">
        <img src="{% static 'img/marvel.png' %}" alt="marvel">
    </div>
</div>
{% endblock %}

MarvelProject/apps/personajes/templates/personajes/crear.html
{% extends 'personajes/index.html'%}
{% load static %}


{%block title%} <h4>Crea tu Personaje de Marvel</h4> {%endblock%}

{% block container%}

<script src="{% static 'js/index.js' %}"></script>

<!-- IMAGEN -->
<div>
    <a class="btn-floating tooltipped" data-position="bottom" data-delay="30" 
        data-tooltip="Regresar" href="{% url 'personajes:list' %}">
        <i class="material-icons">arrow_back</i></a>
</div>

<!-- FORMULARIO -->
<div class="row card" >
    <div class="col s5 hoverable" style="margin-top:60px">
        <img src="{% static 'img/marvel2.jpg' %}" alt="" class=" responsive-img"> <!-- notice the "circle" class -->
    </div>
    <form class="col s7 card-content" method="POST" 
          enctype="multipart/form-data" action="{% url 'personajes:crear-personaje' %}">
        {% csrf_token %}
        <!-- Nombres -->
        <div class="input-field col s12">
            <i class="material-icons prefix">account_circle</i>
            {{form.nombre}}
            <label for="nombre">Nombre de Tu Personaje de Marvel</label>
            
            {% for error in form.nombre.errors %}
                <div class="card-panel red lighten-2">
                    <span class="white-text text-darken-2">{{error}}</span></div>
            {% endfor %}
                
        </div>
        <!-- Tipo Personaje -->
        <div class="input-field col s12">
            <i class="material-icons prefix">account_circle</i>
            {{form.tipo_personaje}}
            <label>Es un Villano o un Héroe?</label>
            {% for error in form.tipo_personaje.errors %}
                <div class="card-panel red lighten-2">
                    <span class="white-text text-darken-2">{{error}}</span></div>
            {% endfor %}
        </div>
        <br>
        <br>
        <!-- Subir Imagen del PErsonaje -->
        <div class="row">
            <div class="input-field col s12">
                {{form.imagen}}
            </div>
            {% for error in form.imagen.errors %}
                <div class="card-panel red lighten-2">
                    <span class="white-text text-darken-2">{{error}}</span></div>
            {% endfor %}
        </div>
        <!-- Descripción -->
        <div class="row">
            <div class="input-field col s12">
                <i class="material-icons prefix">description</i>
                {{form.descripcion}}
                <label for="id_description">Escribe una Descripción del Personaje</label>
            </div>
            {% for error in form.descripcion.errors %}
                <div class="card-panel red lighten-2">
                    <span class="white-text text-darken-2">{{error}}</span></div>
            {% endfor %}
        </div>
        <!--  Guarda el Personaje -->
        <div class="center">
            <button class="btn waves-effect waves-light" type="submit" name="action">Guardar
                <i class="material-icons right">save</i>
            </button>
        </div>
    </form>

    
</div>


{%endblock%}

MarvelProject/apps/personajes/templates/personajes/detail-personaje.html
{% extends 'personajes/index.html'%}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{%endblock%}


{% block container %}
<div>
    <a class="btn-floating tooltipped" data-position="bottom" data-delay="30" 
        data-tooltip="Regresar" href="{% url 'personajes:list' %}">
        <i class="material-icons">arrow_back</i></a>
</div>


<div class="card personaje-detail">
    <div class="row">
        <div class="col s4 m4 l6">
                <br>
            <div class="imagen-detail" style="width:500px">
                {% if object.imagen %}
                    <img class="responsive-img activator" src="{{object.imagen.url}}">
                {%else%}
                <img class="responsive-img activator" src="{{object.imagen_url}}">
                {% endif %}
            </div>
        </div>
        <div class="col s8 m8 l6">
            <div class="nombre">
                <h3 class="teal-text text-darken-2">{{object.nombre}}</h3>
            </div>
            <div class="descripcion">
                <b>Descripcion:</b>
                <p>{{object.descripcion}}</p>
            </div>
            <div class="tipo_personaje">
                <b>Es un :</b>
                <p>{{object.tipo_personaje}}</p>
            </div>
            
            <div class="fecha_creacion">
                <b>Fue Creado el :</b>
                <p>{{object.fecha_creacion}}</p>
            </div>
            <div class="fecha_modificacion">
                <b>Fue Moficado el :</b>
                <p>{{object.fecha_modificacion}}</p>
            </div>
        </div>

    </div>
</div>

<div class="fixed-action-btn">
    <a class="btn-floating btn-large waves-effect waves-light red" 
    href="{% url 'personajes:update' object.pk %}">
    <i class="material-icons">edit</i></a>
</div>


{%endblock%}

MarvelProject/apps/personajes/templates/personajes/extraer_data.html
{% extends 'personajes/index.html'%}

{% block title%} <h5>Obten los Personajes desde la API de Marvel</h5> {% endblock%}

{% block container%}
    <div>
        <a class="btn-floating tooltipped" data-position="bottom" data-delay="30" 
            data-tooltip="Regresar" href="{% url 'personajes:list' %}">
            <i class="material-icons">arrow_back</i></a>
    </div>
    <div class="row">
        <div class="card">
            <div class="row">
                <p class="card-content">
                        CREATE AWESOME STUFF 
                        WITH THE WORLD'S 
                        GREATEST COMIC API
                        The Marvel Comics API allows developers everywhere to access information about Marvel's vast library of comics—from what's coming up, to 70 years ago. 
                </p>
                <form class="col s12" method="POST" action="{% url 'personajes:datos' %}">
                    {%csrf_token%}
                    <div class="row center">
                        <button class="btn waves-effect waves-light" type="submit" name="action">Obtenga los datos
                            <i class="material-icons right">send</i>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

MarvelProject/apps/personajes/templates/personajes/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' %}">
    <title>Primer template</title>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"></script>
    {%block styles%} {%endblock%}
</head>
<body>
    <div class="center">
        {%block title%} {%endblock%}
    </div>

    <div class="container">
        {% block container%}{%endblock%}
    </div>
    
    <script src="{% static 'materialize/js/materialize.min.js' %}"></script>
</body>
</html>

MarvelProject/apps/personajes/templates/personajes/list-personaje.html
{% extends 'personajes/index.html'%}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{%endblock%}

<script src="{% static 'js/index.js' %}"></script>

{%block title%} <h5 class="teal-text text-darken-2">Personajes del Universo de Marvel</h5> {%endblock%}

{% block container%}

<div class="card">
    <div class="card-content">
        Si deseas más datos pulsa
        <a href="{% url 'personajes:datos' %}">Aquí</a>
    </div>
</div>

{% for personaje in object_list %}
    <div class="row personaje">
        <div class="card col">
            <div class="card-image waves-effect waves-block waves-light">
                {% if personaje.imagen %}
                    <img class="activator" src="{{personaje.imagen.url}}">
                {%else%}
                <img class="activator" src="{{personaje.imagen_url}}">
                {% endif %}
            </div>
            <div class="card-content">
                <span class="card-title activator grey-text text-darken-4">{{personaje.nombre}}
                    <i class="material-icons right">more_vert</i></span>
                    <div class="chip">
                        {{personaje.tipo_personaje}}
                        <i class="close material-icons">account_circle</i>
                    </div>
                    <div class="creado">
                        Creado : {{personaje.fecha_creacion}}
                    </div>
                    <p><a href="{% url 'personajes:detail' personaje.pk  %}">Ver Detalle</a></p>
                </div>
                <div class="card-reveal">
                    <span class="card-title grey-text text-darken-4">{{personaje.nombre}}
                          <i class="material-icons right">account_circle</i></span>
                    <p>{{personaje.descripcion}}</p>
                </div>
        </div>
    </div>
    {% endfor %}        

    <div class="fixed-action-btn">
        <a class="btn-floating btn-large waves-effect waves-light red" 
           href="{% url 'personajes:crear-personaje' %}">
            <i class="material-icons">add</i></a>
    </div>
{% endblock %}

MarvelProject/apps/personajes/templates/personajes/update-personaje.html
{% extends 'personajes/index.html'%}
{% load static %}


{%block title%} <h4>Crea tu Personaje de Marvel</h4> {%endblock%}

{% block container%}

<script src="{% static 'js/index.js' %}"></script>

<!-- IMAGEN -->
<div>
    <a class="btn-floating tooltipped" data-position="bottom" data-delay="30" 
        data-tooltip="Regresar" href="{% url 'personajes:list' %}">
        <i class="material-icons">arrow_back</i></a>
</div>

<!-- FORMULARIO -->
<div class="row card" >
    <div class="col s5 hoverable" style="margin-top:20px">
        {% if object.imagen %}
            <img class="responsive-img activator" src="{{object.imagen.url}}">
        {%else%}
        <img class="responsive-img activator" src="{{object.imagen_url}}">
        {% endif %}
    </div>
    <form class="col s7 card-content" method="POST" 
          enctype="multipart/form-data" action="{% url 'personajes:update' object.pk %}">
        {% csrf_token %}
        <!-- Nombres -->
        <div class="input-field col s12">
            <i class="material-icons prefix">account_circle</i>
            {{form.nombre}}
            <label for="nombre">Nombre de Tu Personaje de Marvel</label>
            
            {% for error in form.nombre.errors %}
                <div class="card-panel red lighten-2">
                    <span class="white-text text-darken-2">{{error}}</span></div>
            {% endfor %}
                
        </div>
        <!-- Tipo Personaje -->
        <div class="input-field col s12">
            <i class="material-icons prefix">account_circle</i>
            {{form.tipo_personaje}}
            <label>Es un Villano o un Héroe?</label>
            {% for error in form.tipo_personaje.errors %}
                <div class="card-panel red lighten-2">
                    <span class="white-text text-darken-2">{{error}}</span></div>
            {% endfor %}
        </div>
        <br>
        <br>
        <!-- Subir Imagen del PErsonaje -->
        <div class="row">
            <div class="input-field col s12">
                {{form.imagen}}
            </div>
            {% for error in form.imagen.errors %}
                <div class="card-panel red lighten-2">
                    <span class="white-text text-darken-2">{{error}}</span></div>
            {% endfor %}
        </div>
        <!-- Descripción -->
        <div class="row">
            <div class="input-field col s12">
                <i class="material-icons prefix">description</i>
                {{form.descripcion}}
                <label for="id_description">Escribe una Descripción del Personaje</label>
            </div>
            {% for error in form.descripcion.errors %}
                <div class="card-panel red lighten-2">
                    <span class="white-text text-darken-2">{{error}}</span></div>
            {% endfor %}
        </div>
        <!--  Guarda el Personaje -->
        <div class="center">
            <button class="btn waves-effect waves-light" type="submit" name="action">Guardar
                <i class="material-icons right">save</i>
            </button>
        </div>
    </form>

    
</div>

{%endblock%}